# Rust formatting configuration
#
# This project uses tabs for indentation to allow developers to choose their
# preferred visual width. Set your editor to display tabs at your preferred width
# (e.g., 2, 4, or 8 spaces).

# Use hard tabs instead of spaces
hard_tabs = true

# Rust edition (aligns with Cargo.toml)
edition = "2024"

# Maximum line width before wrapping
max_width = 120

# Maximum width for chained expressions before wrapping
chain_width = 80

# Maximum width for array literals before wrapping
array_width = 80
